### ISSUE TITLE
how to reset the increment of 100 images

### ISSUE THREAD

**Issue by mawed** [mobilecoinofficial/qrhunt#2]
Hey,

I saw there is an increment for sending images, which sends a "Sorry, try again later" after 100 images.

How can I reset this increment or what is the intention of it?

![signal-2022-02-16-22-53-54-047](https://user-images.githubusercontent.com/11197868/154365359-044c5f0f-2b3d-43df-9a46-0964800a5bd3.png)

At least the reaction should be more helpful somehow.

**Comment by itdaniher** [comment]
You can now use the "unlock" command!
